spring.application.name=EduSprint
server.servlet.context-path=/api

spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.datasource.driver-class-name=${spring.datasource.driver-class-name}

spring.jpa.hibernate.ddl-auto=${spring.jpa.hibernate.ddl-auto}

aws.access-key-id=${aws.access-key-id}
aws.secret-access-key=${aws.secret-access-key}
aws.region=${aws.region}
aws.s3-bucket-name=${aws.s3-bucket-name}

turnstile.verify-url=${turnstile.verify-url}
turnstile.secret-key=${turnstile.secret-key}

resend.api-key=${resend.api-key}