spring.application.name=EduSprint
server.servlet.context-path=/api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3-bucket-name=${AWS_S3_BUCKET_NAME}

turnstile.verify-url=${TURNSTILE_VERIFY_URL}
turnstile.secret-key=${TURNSTILE_SECRET_KEY}

resend.api-key=${RESEND_API_KEY}