spring.application.name=EduSprint
server.servlet.context-path=/api

# Postavke za PostgreSQL bazu
spring.datasource.url=jdbc:postgresql://pg-edu-sprint-edu-sprint.h.aivencloud.com:18956/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_x9jCMncQNDbBund7UUr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA i Hibernate konfiguracija
spring.jpa.hibernate.ddl-auto=update

#AMAZON S3
aws.access-key-id=AKIA3A53LHN2PKOHSSEP
aws.secret-access-key=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
aws.region=eu-north-1
aws.s3-bucket-name=matmat-storage

#CLOUDFLARE TURNSTILE
turnstile.verify-url=https://challenges.cloudflare.com/turnstile/v0/siteverify
turnstile.secret-key=0x4AAAAAABBBBQgwuVc3TH9I2fczKv_yv7Y

